### ISSUE TITLE
can't upload artifacts to nexus, can't login nexus portal too

### ISSUE THREAD

**Issue by wangyf2010** [jenkins-x-charts/nexus#12]
I tried out jx last night. While after get all installation done, jenkins complain can't upload artifacts to nexus due to 401 error.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project demo: Failed to deploy artifacts: Could not transfer artifact com.example:demo:jar:0.0.1 from/to local-nexus (http://nexus/repository/maven-releases/): Failed to transfer file: http://nexus/repository/maven-releases/com/example/demo/0.0.1/demo-0.0.1.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
[ERROR] 
```
I went to nexus portal and try to login with "admin:admin123", or  "admin:rabbitblack", can't login it too.
I'm not sure whether my installation something wrong.
I checked maven settings in [here](https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml#L841-L842), it should use "admin:admin123", is that correct?

**Comment by unixhelden** [comment]
After Installation of Jenkins-X you get this message:

Jenkins X installation completed successfully
*******************************************************
   NOTE: Your admin password is: *******
********************************************************
Use the password presented to you to log in into nexus. 

If you didn't note the password, get a shell in the node where jenkins-x has the pod running and look for the java -jar command, it should have the password in the command line.

**Comment by wangyf2010** [comment]
I tried to install jx several times. still have this problem. I know the password: 
`
	********************************************************

	     NOTE: Your admin password is: wolfbrick

	********************************************************`

I can't login nexus portal with admin/wolfbrick too.

**Comment by ccojocar** [comment]
I think this is outdated issue. I am going to close it. Thanks!
