### ISSUE TITLE
Adding jitpack repo failed?

### ISSUE THREAD

**Issue by tdcox** [jenkins-x-charts/nexus#3]
> Using:
> NAME        VERSION
> jx          1.1.5
> Jenkins X   0.0.348
> Kubernetes  v1.9.3-gke.0
> Helm Client v2.8.1+g6af75a8
> Helm Server v2.8.1+g6af75a8
> Git         git version 2.14.3 (Apple Git-98)

The fix to add jitpack.io as a repo doesn't seem to be working as I didn't get the repo in the latest update.

**Comment by ccojocar** [comment]
This seems to be an old issue. I am closing it. Fell free to open another issue if the problem still occurs. Thanks!
