### ISSUE TITLE
postStart.sh exited with 137

### ISSUE THREAD

**Issue by StevenPG** [jenkins-x-charts/nexus#40]
I believe this is the same issue as issue #28 , however they have no detail in their issue.

NAME               VERSION
jx        -         2.0.581
jenkins x platform - 2.0.951
Kubernetes cluster - v1.14.3
kubectl         -   v1.14.3
helm client     -   Client: v2.14.2+ga8b13cc
git        -        2.22.0.windows.1
Operating System -  Windows 10 Pro 1903 build 18362

Events:

 Type     Reason               Age                From                     Message
  ----     ------               ----               ----                     -------

  Normal   Scheduled            30s                default-scheduler        Successfully assigned jx/jenkins-x-nexus-6bc788447f-5dj9c to docker-desktop

  Normal   Pulled               19s (x2 over 29s)  kubelet, docker-desktop  Container image "gcr.io/jenkinsxio/nexus:0.1.7" already present on machine

  Normal   Created              19s (x2 over 29s)  kubelet, docker-desktop  Created container nexus
  
Normal   Started              19s (x2 over 29s)  kubelet, docker-desktop  Started container nexus
  
Warning  FailedPostStartHook  10s (x2 over 20s)  **kubelet, docker-desktop  Exec lifecycle hook ([/opt/sonatype/nexus/postStart.sh]) for Container "nexus" in Pod "jenkins-x-nexus-6bc788447f-5dj9c_jx(6600ed4e-c0f8-11e9-a82a-00155d02e105)" failed - error: command '/opt/sonatype/nexus/postStart.sh' exited with 137: , message: ".."**
  
Normal   Killing              10s (x2 over 20s)  kubelet, docker-desktop  FailedPostStartHook
  
Warning  BackOff              7s (x3 over 9s)    kubelet, docker-desktop  Back-off restarting failed container
`

Docker for Desktop Configuration is as follows:

CPUS: 4

Memory: 8192 MB

Swap: 1024 MB

Disk image max size: 59.6 GB

All of the rest of the pods come up successfully:

crier-576b9854b4-m9nrl                         1/1     Running            1          48m
deck-5f79b74f46-kdxsb                          1/1     Running            1          48m
deck-5f79b74f46-p5g7l                          1/1     Running            1          48m
hook-bf4cdff5c-dgzdf                           1/1     Running            2          48m
hook-bf4cdff5c-jxp86                           1/1     Running            2          48m
horologium-c68d89485-f6pdp                     1/1     Running            1          48m
jenkins-x-chartmuseum-d87cbb789-9pw46          1/1     Running            1          48m
jenkins-x-controllerbuild-757b98b76b-ls2q2     1/1     Running            1          48m
jenkins-x-controllerrole-5f84999ff6-4pft6      1/1     Running            1          48m
jenkins-x-controllerteam-5f7d9649cd-f6hcm      1/1     Running            1          48m
jenkins-x-docker-registry-69d666d455-94858     1/1     Running            1          48m
jenkins-x-heapster-ff6df6848-6lpms             2/2     Running            0          14m
**_jenkins-x-nexus-6bc788447f-5dj9c               0/1     CrashLoopBackOff   6          7m17s_**
pipeline-75bf8bc958-62kpm                      1/1     Running            2          48m
pipelinerunner-597bf69b94-xcpp6                1/1     Running            1          48m
plank-58586dcfdf-fh9tc                         1/1     Running            1          48m
sinker-665545d896-nkndp                        1/1     Running            1          48m
tekton-pipelines-controller-786b485fc5-r2rlr   1/1     Running            1          48m
tekton-pipelines-webhook-56cd88ddb5-xtn4j      1/1     Running            1          48m
tide-75456796f5-x2dhc                          1/1     Running            1          48m

I'm not sure exactly where the 137 is getting thrown from from within the postStart.sh.

**Comment by Rested** [comment]
@StevenPG were you able to figure this out in the end? having the same issue

**Comment by StevenPG** [comment]
@Rested Unfortunately not, it looks like it may have something to do with persistent volumes not being allocated properly. I had an issue on an Ubuntu server with the same error and that was the root. Since Docker for Desktop (windows) does not play very nice with the filesystem (as far as I can tell), I fear you'd need something like portworx or storageOS configured within the Kubernetes installation on windows to resolve it.

I moved onto Ubuntu and didn't investigate this further.

**Comment by AlienResidents** [comment]
@StevenPG, and @Rested, I've seen a similar error before, and for me it was due to a lack of quoting the `$PASSWORD` variables in `postStart.sh`.  In short, if you **do not** have spaces in your passphrase/password, then this might not be your problem.

There is another open issue regarding this which is https://github.com/jenkins-x/jx/issues/3510.  

There is also a PR that fixes this (as soon as I implemented my changes, it has been working ever since) too which is located here: https://github.com/jenkins-x-charts/nexus/pull/39.

Try editing your deployment, and running `sleep 3600`, then `kubectl exec -it <POD> sh`, and then edit `postStart.sh` and quote all `$PASSWORD` variables in that script, and see if it works for you.  It worked for me, an it was only the nexus PODs.

Hope this helps.

**Comment by AlienResidents** [comment]
Also, PR #39 may also fix issue #28 too, if it's the same error.

**Comment by Rested** [comment]
@StevenPG Were you using wsl or plain windows or would that not make a difference? @AlienResidents I don't have a space in my password, tried anyway but same result.

**Comment by StevenPG** [comment]
@Rested, I think that wouldn't make a difference however, Docker for Desktop is outside of WSL. I was running JX through powershell on plain windows.

**Comment by StevenPG** [comment]
Spent some more time on this, out of the box I don't think this is resolveable. Have no issues on Linux, just seems to be something with windows.
