### ISSUE TITLE
Upgrade to more recent version?

### ISSUE THREAD

**Issue by nelsonsilva** [jenkins-x-charts/nexus#41]
This chart is currently relying on a 10 month old 3.15.1 Nexus version and changes have not been pushed upstream to Helm repo (which is now aligned on Nexus 3.17).
We currently need to align with at least Nexus >= 3.16 (due to https://issues.sonatype.org/browse/NEXUS-19384 and because there are a handful of known CVE for Nexus <= 3.15.x  and were wondering how we could do this in a clean way that could hopefully be contributed back. 
I do see at least one PR trying to update to a newer version (https://github.com/jenkins-x-charts/nexus/pull/34) but tests apparently failed and it did not land.

**Comment by ccojocar** [comment]
Updated to 3.20.1.
